//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyFirstMAMVCDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableLog
    {
        public int LogID { get; set; }
        public string EventVal { get; set; }
        public System.DateTime EventDate { get; set; }
        public string ChangedBy { get; set; }
    }
}
