//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyFirstMAMVCDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCourse
    {
        public int CourseID { get; set; }
        public string CourseName { get; set; }
        public int StudentID { get; set; }
    
        public virtual tblStudent tblStudent { get; set; }
    }
}
