//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyFirstMAMVCDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_1
    {
        public int CourseID { get; set; }
        public string CourseName { get; set; }
        public int StudentID { get; set; }
        public int Expr1 { get; set; }
        public string StudentName1 { get; set; }
        public System.DateTime StudentDOB { get; set; }
        public int Gender { get; set; }
        public bool IsPass { get; set; }
        public string Course { get; set; }
        public Nullable<int> Salary { get; set; }
    }
}
